# Generated by Django 3.0.7 on 2020-06-06 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_title', models.CharField(max_length=200)),
                ('test_content', models.TextField()),
                ('test_published', models.DateTimeField(verbose_name='data published')),
            ],
        ),
    ]
